info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T02:42:35.762Z"}
info: Connected to the database. {"timestamp":"2022-02-22T02:42:35.886Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/login 
      method - GET 
      IP - ::ffff:127.0.0.1
     {"timestamp":"2022-02-22T02:43:32.494Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T02:49:30.378Z"}
info: Connected to the database. {"timestamp":"2022-02-22T02:49:30.403Z"}
error: 
    status - 500 
    message - ReferenceError: done is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:113:25)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T02:49:43.443Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T02:50:21.320Z"}
info: Connected to the database. {"timestamp":"2022-02-22T02:50:21.343Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T02:51:17.306Z"}
info: Connected to the database. {"timestamp":"2022-02-22T02:51:17.332Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T02:52:14.064Z"}
info: Connected to the database. {"timestamp":"2022-02-22T02:52:14.093Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T04:30:59.246Z"}
info: Connected to the database. {"timestamp":"2022-02-22T04:30:59.383Z"}
error: 
    status - 500 
    message - Error: User is not Registered
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:123:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:31:12.814Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be at least 10 characters long 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:32:23.141Z"}
error: 
    status - 500 
    message - Error: User is not Registered
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:123:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:32:48.887Z"}
error: 
    status - 500 
    message - Error: User is not Registered
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:123:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:32:52.108Z"}
error: 
    status - 500 
    message - Error: User is not Registered
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:123:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:32:52.981Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T04:33:23.396Z"}
info: Connected to the database. {"timestamp":"2022-02-22T04:33:23.427Z"}
error: 
    status - 500 
    message - ReferenceError: hasedPassword is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:102:56)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:33:32.170Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T04:34:29.336Z"}
info: Connected to the database. {"timestamp":"2022-02-22T04:34:29.381Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:34:37.420Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T04:47:13.849Z"}
info: Connected to the database. {"timestamp":"2022-02-22T04:47:13.872Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:47:35.626Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:47:37.102Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:54:06.132Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:54:07.496Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:54:08.121Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:54:08.534Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:54:08.874Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:55:25.327Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:55:26.499Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:55:27.294Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:57:20.683Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:109:13)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T04:58:05.764Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T05:07:47.775Z"}
info: Connected to the database. {"timestamp":"2022-02-22T05:07:47.810Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T05:36:19.717Z"}
info: Connected to the database. {"timestamp":"2022-02-22T05:36:19.744Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T06:09:52.580Z"}
info: Connected to the database. {"timestamp":"2022-02-22T06:09:52.608Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T06:10:45.459Z"}
info: Connected to the database. {"timestamp":"2022-02-22T06:10:45.493Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T06:12:25.651Z"}
info: Connected to the database. {"timestamp":"2022-02-22T06:12:25.689Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T06:13:46.718Z"}
info: Connected to the database. {"timestamp":"2022-02-22T06:13:46.748Z"}
error: 
    status - 500 
    message - Error: User is not Registered
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:128:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T06:15:12.973Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T06:16:36.933Z"}
info: Connected to the database. {"timestamp":"2022-02-22T06:16:36.962Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T06:20:55.270Z"}
info: Connected to the database. {"timestamp":"2022-02-22T06:20:55.297Z"}
error: 
    status - 500 
    message - Error: password does not match
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:121:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T06:21:04.607Z"}
error: 
    status - 500 
    message - Error: password does not match
    at _callee3$ (C:\Users\anand\Desktop\fundoo-Notes\build\services\user.service.js:121:19)
    at tryCatch (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\anand\Desktop\fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-02-22T08:31:45.894Z"}
