info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-04-05T07:44:52.813Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\anand\\Desktop\\fundoo-Notes\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\regenerator-runtime\\runtime.js:63:40)\n    at Generator.invoke [as _invoke] (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\regenerator-runtime\\runtime.js:294:22)\n    at Generator.next (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\regenerator-runtime\\runtime.js:119:21)\n    at asyncGeneratorStep (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12\n    at database (C:\\Users\\anand\\Desktop\\fundoo-Notes\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (C:\\Users\\anand\\Desktop\\fundoo-Notes\\src\\/index.js:36:1)\n    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n    at Module._compile (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n    at Object.newLoader [as .js] (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\pirates\\lib\\index.js:141:7)","timestamp":"2022-04-05T07:45:22.828Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-04-05T10:48:06.363Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\anand\\Desktop\\fundoo-Notes\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\regenerator-runtime\\runtime.js:63:40)\n    at Generator.invoke [as _invoke] (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\regenerator-runtime\\runtime.js:294:22)\n    at Generator.next (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\regenerator-runtime\\runtime.js:119:21)\n    at asyncGeneratorStep (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12\n    at database (C:\\Users\\anand\\Desktop\\fundoo-Notes\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (C:\\Users\\anand\\Desktop\\fundoo-Notes\\src\\/index.js:36:1)\n    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n    at Module._compile (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n    at Object.newLoader [as .js] (C:\\Users\\anand\\Desktop\\fundoo-Notes\\node_modules\\pirates\\lib\\index.js:141:7)","timestamp":"2022-04-05T10:48:36.340Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-04-05T11:05:06.301Z"}
info: Connected to the database. {"timestamp":"2022-04-05T11:05:06.495Z"}
error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials z7-20020a056a00240700b004e1cde37bc1sm15993896pfh.84 - gsmtp {"code":"EAUTH","command":"AUTH PLAIN","response":"535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials z7-20020a056a00240700b004e1cde37bc1sm15993896pfh.84 - gsmtp","responseCode":535,"timestamp":"2022-04-05T11:39:15.926Z"}
error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 34-20020a17090a0fa500b001cabffcab2csm2183401pjz.55 - gsmtp {"code":"EAUTH","command":"AUTH PLAIN","response":"535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials 34-20020a17090a0fa500b001cabffcab2csm2183401pjz.55 - gsmtp","responseCode":535,"timestamp":"2022-04-05T11:46:12.206Z"}
error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials p28-20020aa79e9c000000b004fafa48f430sm15582996pfq.92 - gsmtp {"code":"EAUTH","command":"AUTH PLAIN","response":"535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials p28-20020aa79e9c000000b004fafa48f430sm15582996pfq.92 - gsmtp","responseCode":535,"timestamp":"2022-04-05T11:48:05.500Z"}
error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials f14-20020a056a0022ce00b004fabe9fac23sm16605838pfj.151 - gsmtp {"code":"EAUTH","command":"AUTH PLAIN","response":"535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials f14-20020a056a0022ce00b004fabe9fac23sm16605838pfj.151 - gsmtp","responseCode":535,"timestamp":"2022-04-05T11:48:22.451Z"}
error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials l27-20020a63701b000000b0038233e59422sm13023286pgc.84 - gsmtp {"code":"EAUTH","command":"AUTH PLAIN","response":"535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials l27-20020a63701b000000b0038233e59422sm13023286pgc.84 - gsmtp","responseCode":535,"timestamp":"2022-04-05T11:49:15.330Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-04-05T13:52:11.754Z"}
info: Connected to the database. {"timestamp":"2022-04-05T13:52:11.839Z"}
error: queryA ETIMEOUT smtp.gmail.com {"code":"EDNS","command":"CONN","hostname":"smtp.gmail.com","syscall":"queryA","timestamp":"2022-04-05T16:21:51.303Z"}
error: queryA ETIMEOUT smtp.gmail.com {"code":"EDNS","command":"CONN","hostname":"smtp.gmail.com","syscall":"queryA","timestamp":"2022-04-05T16:37:29.862Z"}
error: queryA ETIMEOUT smtp.gmail.com {"code":"EDNS","command":"CONN","hostname":"smtp.gmail.com","syscall":"queryA","timestamp":"2022-04-05T16:54:16.531Z"}
error: queryA ETIMEOUT smtp.gmail.com {"code":"EDNS","command":"CONN","hostname":"smtp.gmail.com","syscall":"queryA","timestamp":"2022-04-05T16:54:20.544Z"}
error: queryA ETIMEOUT smtp.gmail.com {"code":"EDNS","command":"CONN","hostname":"smtp.gmail.com","syscall":"queryA","timestamp":"2022-04-05T16:56:29.354Z"}
